---
header-includes:
- \usepackage{lastpage}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[CO, CE]{Kaiyue Wu}
- \fancyfoot[CO, CE]{\thepage \ of \pageref{LastPage}}
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
urlcolor: blue
---


```{r setup, echo=FALSE, message=FALSE}

library(tidyverse)
library(readxl)
library(janitor)
library(opendatatoronto)
library(ggthemes)
library(lubridate)

knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), echo = FALSE)
```


```{r load_data, echo=FALSE}
daily_data <- "data/CityofToronto_COVID-19_Daily_Public_Reporting.xlsx"

reported_raw <- read_excel(daily_data, sheet = 5) %>% 
  clean_names()


outbreak_raw <- read_excel(daily_data, sheet = 4) %>% 
  clean_names()

# When was this data updated?
date_daily <- read_excel(daily_data, sheet = 1) %>% 
  clean_names()

# By neighbourhood
neighbourood_data <- "data/CityofToronto_COVID-19_NeighbourhoodData.xlsx"

# Cases reported by date
nbhood_raw <- read_excel(neighbourood_data, sheet = 2) %>% 
  clean_names()

# Date the neighbourhood data was last updated
date_nbhood <- read_excel(neighbourood_data, sheet = 1) %>% 
  clean_names()

#don't need these anymore
rm(daily_data, neighbourood_data)

#############################################################

# Get neighbourhood profile data
nbhood_profile <- readRDS("data/neighbourhood_profile.Rds")

# Get shape data for mapping 
nbhoods_shape_raw <- readRDS("data/neighbourhood_shapefile.Rds") %>% 
  sf::st_as_sf() ## Makes sure shape info is in the most up to date format

```

# Daily cases

```{r cases_dw}
reported <- reported_raw %>%
  mutate_if(is.numeric, replace_na, replace = 0) %>%
  mutate(reported_date = date(reported_date)) %>%
  rename(Active = active, Recovered = recovered, Deceased = deceased, Date = reported_date) %>%
  pivot_longer(-c(Date), names_to = "type", values_to = "Case_Count") %>%
  mutate(type = fct_relevel(type, "Recovered", after = 1))
```

```{r cases_vis}
reported %>%
  ggplot(aes(x = Date, y = Case_Count, fill = type)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(limits = c(0, 2000)) +
  scale_x_date(labels = scales::date_format("%d %b %y"), limits = c(date("2020-01-01"), Sys.Date())) +
  scale_fill_manual(values = c("Active" =  "#003F5C", "Recovered" =  "#86BCB6",
                               "Deceased" =  "#B9CA5D")) +
  theme_minimal() +
  labs(title = "Cases reported by day in Toronto, Canada",
       subtitle = "Confirmed and probable cases",
       y = "Case count",
       caption = str_c("Created by: Kaiyue Wu for STA303/1002, U OF T\n",
                       "Source: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n",
                       date_daily[1,1])) +
  theme(legend.title = element_blank(), legend.position = c(.15, .8))
```

\newpage
# Outbreak type


```{r outbreak_dw}
outbreak <- outbreak_raw %>%
  mutate_if(is.numeric, replace_na, replace = 0) %>%
  mutate(reported_week = date(reported_week)) %>%
  mutate(outbreak_or_sporadic = str_replace(outbreak_or_sporadic,
                                            "OB Associated", "Outbreak associated")) %>%
  mutate(outbreak_or_sporadic = fct_relevel(outbreak_or_sporadic,
                                            "Outbreak associated", after = 1)) %>%
  group_by(reported_week) %>%
  mutate(total_cases = sum(cases))
```


```{r outbreak_vis, warning= FALSE}
outbreak %>%
  ggplot(aes(x = reported_week, y = cases, fill = outbreak_or_sporadic)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(limits = c(0, 8000)) +
  scale_x_date(labels = scales::date_format("%d %b %y"), limits = c(date("2020-01-01"), Sys.Date())) +
  scale_fill_manual(values = c("Outbreak associated" =  "#B9CA5D", "Sporadic" =  "#86BCB6")) +
  theme_minimal() +
  labs(title = "Cases by outbreak type and week in Toronto, Canada",
       subtitle = "Confirmed and probable cases",
       y = "Case count",
       caption = str_c("Created by:Kaiyue Wu for STA303/1002, U OF T\n",
                       "Source: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n",
                       date_daily[1,1])) +
  theme(legend.title = element_blank(), legend.position = c(.15, .8))
```

\newpage
# Neighbourhoods

```{r nbhood_dw_1}
income <- nbhood_profile %>%
  filter(Alderwood == "7.9") %>%
  pivot_longer(-c(`_id`, Category, Topic, `Data Source`, Characteristic),
               names_to = "neighbourhood", values_to = "percentage") %>%
  select(neighbourhood, percentage) %>%
  rename(neighbourhood_name = neighbourhood) %>%
  mutate(neighbourhood_name = str_replace(neighbourhood_name, "Pelham", "Pellam")) %>%
  mutate(neighbourhood_name = str_replace(neighbourhood_name,
                                          "North St. James Town", "North St.James Town")) %>%
  mutate(neighbourhood_name = str_replace(neighbourhood_name,
                                          "Cabbagetown-South St. James Town",
                                          "Cabbagetown-South St.James Town")) %>%
  mutate(percentage = as.numeric(percentage))
```


```{r nbhood_dw_2}
nbhood_raw <- nbhood_raw %>%
  mutate(neighbourhood_name = str_replace(neighbourhood_name,
                                          "North St. James Town", "North St.James Town")) %>%
  mutate(neighbourhood_name = str_replace(neighbourhood_name, "Pelham", "Pellam")) %>%
  mutate(neighbourhood_name = str_replace(neighbourhood_name,
                                          "Cabbagetown-South St. James Town",
                                          "Cabbagetown-South St.James Town"))

nbhoods_all <- nbhoods_shape_raw %>%
  mutate(neighbourhood_name = str_remove(AREA_NAME, "\\s\\(\\d+\\)$")) %>%
  left_join(nbhood_raw, by = "neighbourhood_name") %>%
  left_join(income, by = "neighbourhood_name") %>%
  rename(rate_per_100000 = rate_per_100_000_people) %>%
  select(neighbourhood_name, rate_per_100000, percentage)
```


```{r nbhood_dw_3}
median_income <- median(nbhoods_all$percentage)
median_rate <- median(nbhoods_all$rate_per_100000)
nbhoods_final <- nbhoods_all %>%
  mutate(med_inc = median_income) %>%
  mutate(med_rate = median_rate) %>%
  mutate(nbhood_type = case_when(
    percentage >= med_inc & rate_per_100000 >= med_rate ~ "Higher low income rate, higher case rate",
    percentage >= med_inc & rate_per_100000 < med_rate ~ "Higher low income rate, lower case rate",
    percentage < med_inc & rate_per_100000 >= med_rate ~ "Lower low income rate, higher case rate",
    percentage < med_inc & rate_per_100000 < med_rate ~ "Lower low income rate, lower case rate"
  ))
```


```{r neighbourhood_graphs_1, fig.height=4, warning= FALSE}
ggplot(data = nbhoods_final) +
  geom_sf(aes(fill = percentage)) +
  theme_map() +
  scale_fill_gradient(name= "% low income", low = "darkgreen", high = "lightgrey") +
  labs(title = "Percentage of 18 to 64 year olds living in a low income family (2015)",
       subtitle = "Neighbourhoods of Toronto, Canada",
       caption = str_c("Created by: Kaiyue Wu for STA303/1002, U of T\n",
                       "Source: Census Profile 98-316-X2016001 via OpenData Toronto\n",
                       date_daily[1,1])) +
  theme(legend.position = c(1, 0))
```

```{r neighbourhood_graphs_2, fig.height=4, warning= FALSE}
ggplot(data = nbhoods_final) +
  geom_sf(aes(fill = rate_per_100000)) +
  theme_map() +
  scale_fill_gradient(name= "Cases per 100,000 people", low = "white", high = "darkorange") +
  labs(title = "COVID-19 CASES PER 100,000, by neighbourhood in Toronto, Canada",
       caption = str_c("Created by: Kaiyue Wu for STA303/1002, U of T\n",
                       "Source: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n",
                       date_daily[1,1])) +
  theme(legend.position = c(.78, 0))
```


```{r neighbourhood_graphs_3, fig.height=4, warning= FALSE}
ggplot(data = nbhoods_final) +
  geom_sf(aes(fill = nbhood_type)) +
  theme_map() +
  scale_fill_brewer(palette = "Set1") +
  labs(title = "COVID−19 cases per 100,000, by neighbourhood in Toronto, Canada",
       caption = str_c("Created by: Kaiyue Wu for STA303/1002, U of T\n",
                       "Income data source: Census Profile 98−316−X2016001 via OpenData Toronto\n",
                       "COVID data source: Ontario Ministry of Health, Integrated Public\n",
                       "Health Information System and CORES\n",
                       date_daily[1,1])) +
  theme(legend.position = c(.7, 0))
```


# References
1. Toronto Public Health. COVID-19 Cases in Toronto. Retrieved from https://open.toronto.ca/dataset/covid-19-cases-in-toronto/

2. Liza Bolton. sta303_data_exploration_template. Retrieved from University of Toronto Quercus

